name: Android CI - Build and Telegram Upload

on:
  workflow_dispatch:  # Allows manual triggering
  push:               # Optional: also run on push to main
    branches:
      - main

jobs:
  build-and-notify:
    name: Build APK and Notify Telegram
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      # Step 3: Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Step 4: Build Release APK
      - name: Build Release APK
        env:
          SKETCHUB_API_KEY: ${{ secrets.SKETCHUB_API_KEY }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          if [ -n "$GOOGLE_SERVICES_JSON" ]; then
            echo "$GOOGLE_SERVICES_JSON" > app/google-services.json
          fi
          gradle assembleRelease

      # Step 5: Rename APK with short commit hash
      - name: Rename APK
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          mv app/build/outputs/apk/release/app-release.apk \
             app/build/outputs/apk/release/app-release-$SHORT_SHA.apk
          echo "APK_PATH=app/build/outputs/apk/release/app-release-$SHORT_SHA.apk" >> $GITHUB_ENV
          echo "APK_NAME=app-release-$SHORT_SHA.apk" >> $GITHUB_ENV

      # Step 6: Upload APK as artifact (optional)
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: ${{ env.APK_PATH }}

      # Step 7: Send to Telegram group topic
      - name: Notify Telegram group
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID || '-1002136675546' }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN || '8034519004:AAGk0Zu1KmAWztdNt52dRqAjPIWCw74Ok5Y' }}
          message_thread_id: ${{ secrets.TELEGRAM_TOPIC_ID || '3481' }}
          document: ${{ env.APK_PATH }}
          caption: |
            🚀 New Sketchware Pro Build!
            📅 Build date: $(date +'%Y-%m-%d %H:%M:%S')
            🔖 Commit: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
            📦 Download the APK above!
